apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress-gateway
spec:
  profile: empty
  components:
    ingressGateways:
      - namespace: istio-system
        name: ingressgateway
        enabled: true
        label:
          istio: ingressgateway
        k8s:
          resources:
            requests:
              cpu: 100m
              memory: 160Mi
            limits:
              cpu: 200m
              memory: 256Mi
          service:
            type: LoadBalancer
            loadBalancerIP: 10.0.0.35
            ports:
              - port: 15021
                targetPort: 15021
                name: status-port
                protocol: TCP
              - port: 15012
                targetPort: 15012
                name: tcp-istiod
                protocol: TCP
              - port: 443
                targetPort: 8443
                name: https
                protocol: TCP