- hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconf | default('/Users/ysung/.kube/config')}}"
  tasks:
  - name: create prometheus namespace
    kubernetes.core.k8s:
      name: prometheus-system
      api_version: v1
      kind: Namespace
      state: present
  - name: install prometheus
    kubernetes.core.helm:
      name: prometheus
      release_namespace: prometheus-system
      chart_ref: prometheus-community/prometheus
      update_repo_cache: true
      values:
        prometheus-pushgateway:
          enabled: false
        alertmanager:
          enabled: false
        service:
          annotations:
            metallb.universe.tf/loadBalancerIPs: 10.10.0.41
            metallb.universe.tf/ip-allocated-from-pool: default-pool
          type: LoadBalancer
        extraScrapeConfigs: |
          - job_name: opencost
            honor_labels: true
            scrape_interval: 1m
            scrape_timeout: 10s
            metrics_path: /metrics
            scheme: http
            dns_sd_configs:
            - names:
              - opencost.opencost
              type: 'A'
              port: 9003
  - name: create opencost namespace
    kubernetes.core.k8s:
      name: kubecost
      api_version: v1
      kind: Namespace
      state: present
  - name: install opencost
    kubernetes.core.helm:
      name: opencost
      chart_ref: opencost/opencost
      release_namespace: kubecost
      values:
        service:
          annotations:
            metallb.universe.tf/loadBalancerIPs: 10.10.0.43
            metallb.universe.tf/ip-allocated-from-pool: default-pool
          type: LoadBalancer
  - name: install grafana
    kubernetes.core.helm:
      name: grafana
      chart_ref: grafana/grafana
      release_namespace: prometheus-system
      values:
        service:
          type: LoadBalancer
          annotations:
            metallb.universe.tf/ip-allocated-from-pool: default-pool
            metallb.universe.tf/loadBalancerIPs: 10.10.0.42            

    